version: "3.9"

services:
  auth:
    extends:
      file: docker-compose.base.yml
      service: auth
    container_name: auth_container
    command: gunicorn wsgi_app:app -b 0.0.0.0:5000 --reload
    expose:
      - 5000
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    extends:
      file: docker-compose.base.yml
      service: db
    container_name: db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    container_name: redis_container

volumes:
  postgres_data:
    name: postgres_data
